### ISSUE TITLE
Decrypt in command line

### ISSUE THREAD

**Issue by jwojt** [travist/jsencrypt#93] opened 2016-12-16 22:38 UTC
The library is great and it is exactly what I need. I generated 2K key and wrote code to encrypt. I can decrypt using JS code in browser, but what I need is ability to decrypt in command line on linux.
When trying: openssl rsautl -decrypt -inkey rsa_1024_priv.pem
I'm getting error:
RSA operation error
140735882023944:error:0406506C:rsa routines:RSA_EAY_PRIVATE_DECRYPT:data greater than mod len:rsa_eay.c:518:
Which I believe means that algorithms are not compatible. 

The question is, can messages be decrypted using openssl, and if not how to do it from command line.
Thanks!

**Comment by MKorostoff** [comment] 2016-12-19 19:04
Came here wondering the exact same thing

**Comment by MKorostoff** [comment] 2016-12-19 21:24
I solved it!  Here's how:

```
base64 -D encrypted_message.txt > binary_messge.txt
openssl rsautl -decrypt -in binary_message.txt -out decrypted_message.txt -inkey rsa_1024_priv.pem
```

Basically, the issue is that the encrypted text is a base64 encoded binary.  You need to base64 decode the message before you can decrypt it.

**Comment by jwojt** [comment] 2016-12-20 02:18
Thanks Much! Works perfect!

**Comment by MKorostoff** [comment] 2016-12-20 13:57
You're very welcome @jwojt.  You probably should close this issue now, so it doesn't pollute the open issue queue.

**Closed** 2016-12-20 20:49 UTC
