### ISSUE TITLE
Support signing with private key and signature verification with public key

### ISSUE THREAD

**Issue by fujifish** [travist/jsencrypt#2] opened 2013-06-18 11:48 UTC
Currently it's only possible to encrypt using the Public key and decrypt using the private key. It's not possible to encrypt using the private key and decrypt using the public key for signature verification.

This feature is absolutely a MUST for me, and I really want to stick with this library instead of using one of the other "heavy" libraries out there.

**Comment by thebestclass** [comment] 2015-04-11 13:21
Someone has addressed these problems? It is not possible that a good library so need to stay still for lack of time the creators ..

**Comment by thebestclass** [comment] 2015-04-11 13:22
@zoloft  @khatribharat @rushglen Someone has addressed these problems? It is not possible that a good library so need to stay still for lack of time the creators ..

**Comment by zoloft** [comment] 2015-04-11 13:31
I'm replying without being able to check the repo now. The problem is not only time issues of the creator (although is partially a problem for me, my main issue is not being able to contribute to code since I'm on contract) but also that the few contributors we had didn't take the time to write tests for their code and I'm really reluctanct to accept code that is not being tested. I'll be on contract until september but my contract could be extended at any time... I agree with you that is a shame that this project is lacking of active contributors and I would LOVE to finish the work in progress I have (see development branches) but I really can't :(



Antonio Egizio

**Comment by thebestclass** [comment] 2015-04-11 16:18
@zoloft I think that if each of half an hour of your day to read the code review and give some thought to develop in a maximum of one month would be running the script. It would be the first library of this kind with JavaScript .. I needed her to use on a large scale but I'm not hard on JavaScript and RSA is not myself continue the project.

You know at least the signature that can be generated above is functional?

or guide me as to why that is not the signature verification work?

**Comment by thebestclass** [comment] 2015-04-11 20:42
@travist

**Comment by travist** [comment] 2015-04-12 03:55
@thebestclass - it sounds like you are ordering us to contribute our time on your behalf. I am not sure how long you have been involved with Open Source, but that is not how it works. We all owe @zoloft a significant amount for his contributions he has already committed. We will eventually get to this problem... If you wish to expedite it, then maybe it would be beneficial to open up a bounty so that @zoloft can get some fiscal reward for all his hard work.

**Comment by thebestclass** [comment] 2015-04-12 15:47
@travist Do not get me wrong, it's not for me but for all who need it client-side (JavaScript) If you seek does not exist any library to do all this while.

If you think you've contributed enough okay ..

I solved my problem tonight as follows, took the JSRASIGN library and cleaned all the null code, and merge it to JSENCRYPT making it just a library (I added only 600 code lines for check / creation signatures worked) Good part of the code you guys already had in the library .. If contrutiva worth a criticism, not put all the code in scope as it was done, it is harmful in some cases needed .. not spend anything beyond my time will soon publish when perfected, hugs!

**Comment by zoloft** [comment] 2015-04-14 14:24
@travist lol :) Thank you but the problem is not the money (nor I want money for the efforts I already/will put in the project) my problem is merely time&legal.
@thebestclass as for your question regarding this code being functional or not, should be pretty easy to write a couple of test case to check if it is

**Comment by fresheneesz** [comment] 2016-04-02 19:01
@travist I didn't see you acknowledge that it is in fact possible to decrypt a message with a public key - if it was encrypted with the private key. That's how RSA authentication works. I'm honestly flabbergasted that someone who doesn't know that created this library...

**Comment by koush** [comment] 2016-05-18 07:29
I tried to use this, but ended up just using web crypto.

```javascript
    
    var signature = base64ToArrayBuffer(d.cachedLicense.signature);
    var signedData = str2ab(d.cachedLicense.signed_data);

    window.crypto.subtle.importKey(
        "jwk", //can be "jwk" (public or private), "spki" (public only), or "pkcs8" (private only)
        {   //this is an example jwk key, other key types are Uint8Array objects
            kty: "RSA",
            e: "AQAB",
            n: "vMGBBmLcMO4lOmg-YAHq2DjZKHTaW-xs9KPNXU_zKJ7ZhFhWH3I6skF9ZO8lKeXOSwVEIW4HVMa7m16S6WTrUw",
            alg: "RS1",
        },
        {   //these are the algorithm options
            name: "RSASSA-PKCS1-v1_5",
            hash: {name: "SHA-1"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
        },
        true, //whether the key is extractable (i.e. can be used in exportKey)
        ["verify"] //"verify" for public key import, "sign" for private key imports
    )
    .then(function(publicKey){
        //returns a publicKey (or privateKey if you are importing a private key)
      window.crypto.subtle.verify(
          {   //these are the algorithm options
              name: "RSASSA-PKCS1-v1_5",
              hash: {name: "SHA-1"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
          },
          publicKey, //from generateKey or importKey above
          signature, //ArrayBuffer of the signature
          signedData //ArrayBuffer of the data
      )
      .then(function(isvalid) {
        if (!isvalid) {
          console.error('invalid signature');
          checkServer();
          return;
        }

        var data = JSON.parse(d.cachedLicense.signed_data);
        if (data.date > Date.now()) {
          console.log('cached license date from future?');
          checkServer();
          return;
        }

        if (data.date + 24 * 60 * 60 * 1000 < Date.now()) {
          console.log('cached license is expired.');
          checkServer();
          return;
        }
        
        checkPayments(data.payments);
        if (!this.isLicensed()) {
          checkServer();
          return;
        }
        
        console.log('cached license is valid for ' + ((data.date + 24 * 60 * 60 * 1000 - Date.now()) / (60 * 60 * 1000)) + ' hours')
        this.licenseCached = true;
        doCallback();
      }.bind(this))
      .catch(function(err){
        console.error('cached license check failed', err);
        checkServer();
      });
    }.bind(this))
    .catch(function(err){
        console.error('key import failed', err);
        checkServer();
    });
  }.bind(this))
}
```

**Comment by xudao520** [comment] 2016-08-26 02:25
@fujifish I have a idea can solve the problem, client take serve_publicKey, client_privateKey and serve take client_publicKey , serve_privateKey . so client encrypt data with serve_publicKey ,server decrypt with serve_privateKey and server encrypt data with client_publicKey ,client decrypt with client_privateKey

**Comment by briantbutton** [comment] 2016-09-18 15:24
@thebestclass did you put the results of your efforts in a repository somewhere.  I cannot find it?

**Comment by travist** [comment] 2018-06-25 17:19
This is now fixed with latest release from @Spark-NF

**Closed by travist** 2018-06-25 17:19 UTC
